spring.security.user.name=username
spring.security.user.password=password


spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/benth_2023
spring.datasource.username=server_user
spring.datasource.password=1234567
#spring.datasource.username=first
#spring.datasource.password=first


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework=debug